# Generated by Django 3.2.5 on 2022-08-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_file',
            field=models.FileField(default='', upload_to='featured_file/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
